title: Flarebird OS
description: An Flarebird OS Distribution for Creatives Everywhere :)
url: "https://FlarebirdOS.github.io"
username: Flarebird OS
user_description: Flarebird OS is a rolling-release distribution aimed at Creative Multi-Media 和 Gaming Enthusiasts.
user_title: An Flarebird OS Operating System
email: xhaa123@outlook.com
github_username:  Flarebird OS
show_downloads: true
google_analytics:
exclude: ['package.json', 'src' , 'node_modules', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
theme: jekyll-theme-hacker
